### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Function name must be a string in /src/Aduanizer/Adapter/PDOAdapter.php:56

### ISSUE THREAD

**Issue by llagerlof** [garotosopa/aduanizer#3]
**Environment:**

  - Windows 8.1
  - PHP 7.2.4
  - Terminal: cygwin
  - Terminal encoding: UTF-8

**Database:**

  - MySQL 5.5.5-10.1.31-MariaDB
  - Engine: InnoDB
  - Default charset: utf8
  - Default collation: utf8_general_ci
  - All tables uses CHARSET=utf8

**How to reproduce:**

Try to import some records to a empty MySQL database with same tables as the source database.
```
$ ./bin/aduanizer -i my_exported_data.yml -a my_destination_database.yml -m map.yml
```

**Comment by garotosopa** [comment]
Fixed in ad75752.
